
const CDN = 'https://cdn.prod.website-files.com/68fa61ebe2c713df4f71a68c/';

// Pitch migration: izakaya→izy, net→other, media→other
function migratePitch(arr) {
  const map = {jpyr:'jpyr', sto:'sto', izakaya:'izy', net:'other', media:'other'};
  return [...new Set(arr.map(p => map[p] || 'other'))];
}

const speakers = [
  // ★★★ HIGH PRIORITY
  {jp:'パオロ・アルドイーノ', en:'Paolo Ardoino', company:'Tether', role:'CEO', cat:'ステーブルコイン', catEn:'Stablecoin', desc:'世界最大のステーブルコインUSDT発行元TetherのCEO。ヘッドラインスピーカー。ステーブルコイン市場の最重要人物。JPYR（JPYステーブルコイン）のベンチマーク・提携候補として最重要。', descEn:'CEO of Tether, issuer of USDT — the world\'s largest stablecoin. Headline speaker. The most important figure in the stablecoin market. Top priority benchmark and partnership candidate for JPYR (JPY stablecoin).', photo:null, priority:'high', pitch:['jpyr'], isNew:true},
  {jp:'ジャック・マラーズ', en:'Jack Mallers', company:'Strike / Twenty One', role:'Founder, CEO', cat:'決済', catEn:'Payments', desc:'BitcoinライトニングネットワークPayment \"Strike\" のCEO。Michael Saylor出資のBTC積み立て企業Twenty OneのCEOも兼務。世界最大級のBitcoin決済インフラを運営。', descEn:'CEO of Strike, a Bitcoin Lightning Network payment platform. Also CEO of Twenty One, a BTC accumulation company backed by Michael Saylor. Operates one of the world\'s largest Bitcoin payment infrastructures.', photo:'69a700294d8a7f5740ab35d6_8c523bd71bea2a10339e1057.webp', priority:'high', pitch:['jpyr'], isNew:true},
  {jp:'デビッド・マーカス', en:'David Marcus', company:'Lightspark', role:'CEO', cat:'決済・Fintech', catEn:'Payments/Fintech', desc:'元PayPal社長、元Meta（Libra/Diem）決済・暗号資産責任者。現在はBitcoinのライトニング決済インフラLightsparkを経営。決済ネットワークの世界的権威。', descEn:'Former PayPal President, former Meta (Libra/Diem) head of payments & crypto. Currently runs Lightspark, a Bitcoin Lightning payment infrastructure. Global authority on payment networks.', photo:'699dd5f3c2e771455be54a6b_7f9d35a485ae8e0c1ce3f563.webp', priority:'high', pitch:['jpyr'], isNew:true},
  {jp:'デイブ・リプレー', en:'Dave Ripley', company:'Kraken', role:'co-CEO', cat:'取引所', catEn:'Exchange', desc:'世界大手暗号資産取引所KrakenのCEO。JPYR上場の最優先候補。Krakenは機関投資家から個人まで幅広いユーザー基盤を持つ。', descEn:'CEO of Kraken, a major global crypto exchange. Top priority candidate for JPYR listing. Kraken serves a broad user base from institutional to retail investors.', photo:'69b40f46edfb35e8245faf34_6cf27b2a991dc42ce1c218b9.webp', priority:'high', pitch:['jpyr'], isNew:true},
  {jp:'アレックス・レイシュマン', en:'Alex Leishman', company:'River', role:'Founder & CEO', cat:'取引所', catEn:'Exchange', desc:'Bitcoin専門の米国取引所River Financialの創業者兼CEO。Bitcoin onlyの純粋主義的取引所として信頼が高い。JPYR上場・統合の有力候補。', descEn:'Founder & CEO of River Financial, a Bitcoin-only US exchange. Highly trusted as a purist Bitcoin exchange. Strong candidate for JPYR listing and integration.', photo:'6987428df098b216e0bd5000_gBHwn9lQb05NhqAKXNHuzXTtMNE2Tyuv58VdkB2MGtI.webp', priority:'high', pitch:['jpyr'], isNew:true},
  {jp:'JP・リチャードソン', en:'JP Richardson', company:'Exodus', role:'CEO & Co-Founder', cat:'ウォレット', catEn:'Wallet', desc:'マルチアセット暗号資産ウォレット「Exodus」の共同創業者兼CEO。月間アクティブユーザー数百万人。JPYR上場＋IZAKAYAウォレット連携の両方で有力候補。', descEn:'Co-founder & CEO of Exodus, a multi-asset crypto wallet with millions of monthly active users. Strong candidate for both JPYR listing and IZAKAYA wallet integration.', photo:'69aae2762b9de129861d7ac7_23f753a2d81100ea57afce0d.webp', priority:'high', pitch:['jpyr','izakaya'], isNew:true},
  {jp:'マイク・ベルシー', en:'Mike Belshe', company:'BitGo', role:'Founder & CEO', cat:'カストディ', catEn:'Custody', desc:'機関投資家向けデジタル資産カストディ最大手BitGoの創業者。NYSE上場(BTGO)。元GoogleのChrome初期エンジニア、HTTP/2.0の共同設計者。STOトークン構造で必要な機関向けカストディとして重要。', descEn:'Founder of BitGo, the largest institutional digital asset custodian. NYSE listed (BTGO). Former early Google Chrome engineer and HTTP/2.0 co-designer. Important as institutional custody for STO token structure.', photo:null, priority:'high', pitch:['sto','jpyr'], isNew:false},
  {jp:'アーサー・ヘイズ', en:'Arthur Hayes', company:'Maelstrom', role:'CIO', cat:'投資家', catEn:'Investor', desc:'BitMEXの共同創業者（クリプト初のユニコーン）。現在はファミリーオフィスMaelstromのCIOとしてクリプト・Web3投資を主導。影響力が極めて高く、STOトークン初期投資家として最重要候補。', descEn:'Co-founder of BitMEX (crypto\'s first unicorn). Currently CIO of family office Maelstrom, leading crypto/Web3 investments. Extremely influential — top candidate as early STO token investor.', photo:'6915efd0e28481890fe01ec3_Ft2J0kfBEnFOBMfQFOVHGlI6eNInQcgcAWGBlzrNGPg.webp', priority:'high', pitch:['sto'], isNew:false},
  {jp:'ジェフ・ブース', en:'Jeff Booth', company:'Ego Death Capital', role:'General Partner', cat:'VC・投資家', catEn:'VC/Investor', desc:'Ego Death CapitalのファウンディングパートナーVC。著書『The Price of Tomorrow』でデフレ経済とBitcoinの関係を論じた。Bitcoin特化VC、STOトークンの初期投資家・アドバイザー候補として最重要。', descEn:'Founding partner at Ego Death Capital VC. Author of "The Price of Tomorrow" on deflation economics and Bitcoin. Top candidate as Bitcoin-focused VC, early STO token investor and advisor.', photo:'69b8484d6ff3f2b01523296c_kqDbP-d1SRSqClWxz5T2dKXbw9SygeYCNtyculUAqUg.webp', priority:'high', pitch:['sto'], isNew:false},
  {jp:'サイモン・ジェロビッチ', en:'Simon Gerovich', company:'Metaplanet', role:'CEO', cat:'投資家・経営者', catEn:'Investor/Executive', desc:'東証上場「Metaplanet」のCEO。日本版MicroStrategyとして大量BTC保有。🇯🇵 日本語対応可能。R Inc.とは同じ日本発グローバルBTC戦略として最も親和性が高い。JPYR・STOトークン両方で連携可能。', descEn:'CEO of TSE-listed Metaplanet, Japan\'s MicroStrategy with massive BTC holdings. 🇯🇵 Japanese-speaking. Highest affinity with R Inc. as a Japan-based global BTC strategy. Potential for both JPYR and STO token collaboration.', photo:'69bdddaad872e37ab52901c0_7te4p_qLUu_YJt2dxQE-DsEmkoxnqA17gmMsuwhjakY.webp', priority:'high', pitch:['jpyr','sto'], isNew:true},
  {jp:'アレクサンダー・ブルーム', en:'Alexander Blume', company:'Two Prime', role:'CEO', cat:'投資', catEn:'Investment', desc:'Two Prime CEOはBitcoin特化インベストメントファーム。機関投資家向けBitcoin金融サービスを提供。STOトークンのファンドパートナー候補として高優先度。', descEn:'CEO of Two Prime, a Bitcoin-focused investment firm providing institutional Bitcoin financial services. High priority candidate as STO token fund partner.', photo:'69b9607d95d1faca2266e232_36233596ed7aaad598866a81.webp', priority:'high', pitch:['sto'], isNew:true},

  // ★★ MED PRIORITY
  {jp:'ティム・ドレイパー', en:'Tim Draper', company:'Draper Associates', role:'Founder', cat:'VC・投資家', catEn:'VC/Investor', desc:'シリコンバレーの伝説的VC。Skype、Tesla、SpaceX、Coinbase等に初期投資。Bitcoin強気派として著名。ヘッドラインスピーカー。STOトークンの初期投資家・権威付けとして最重要級。', descEn:'Legendary Silicon Valley VC. Early investor in Skype, Tesla, SpaceX, Coinbase. Well-known Bitcoin bull. Headline speaker. Top-tier candidate for STO token early investor and endorsement.', photo:null, priority:'med', pitch:['sto'], isNew:true},
  {jp:'エイミー・オルデンバーグ', en:'Amy Oldenburg', company:'Morgan Stanley', role:'Head of Digital Asset Strategy', cat:'機関投資家', catEn:'Institutional Investor', desc:'Morgan Stanleyのデジタル資産戦略責任者。世界最大級の金融機関からの参加。STOトークンの機関投資家パートナーとして超有望。', descEn:'Head of Digital Asset Strategy at Morgan Stanley. Participation from one of the world\'s largest financial institutions. Extremely promising as an institutional investor partner for STO token.', photo:null, priority:'med', pitch:['sto'], isNew:true},
  {jp:'タレク・マンスール', en:'Tarek Mansour', company:'Kalshi', role:'Co-Founder & CEO', cat:'予測市場', catEn:'Prediction Market', desc:'CFTC規制の予測市場プラットフォームKalshiのCEO。規制対応フィンテックのリーダー。IZAKAYAウォレット連携候補。', descEn:'CEO of Kalshi, a CFTC-regulated prediction market platform. Leader in regulatory-compliant fintech. Candidate for IZAKAYA wallet integration.', photo:null, priority:'med', pitch:['izakaya'], isNew:true},
  {jp:'マイケル・セイラー', en:'Michael Saylor', company:'Strategy', role:'Founder & Executive Chairman', cat:'投資家・経営者', catEn:'Investor/Executive', desc:'ビットコイン最大の法人保有者。StrategyはBTC700億円超を保有する上場企業。Bitcoin標準の最も著名な提唱者。STOトークンの権威付け・アドバイザーとして名前を使えれば大きい。', descEn:'Largest corporate Bitcoin holder. Strategy is a public company holding 70B+ yen in BTC. Most prominent advocate of the Bitcoin standard. Having his name as STO token authority/advisor would be significant.', photo:'6972a319649d47b55c230191_N_DTZy4vdL3S85JV5FQvEYJ7IEU9wAIyjyE8Rad58lc.webp', priority:'med', pitch:['sto'], isNew:false},
  {jp:'フォング・レ', en:'Phong Le', company:'Strategy', role:'President & CEO', cat:'投資家', catEn:'Investor', desc:'StrategyのCEO（Michael Saylor直下）。実務的意思決定はPhong Leが担う。STOトークンとStrategy/MicroStrategyモデルの類似性から話が合いやすい。', descEn:'CEO of Strategy (directly under Michael Saylor). Handles practical decision-making. Natural conversation given the similarity between STO token and Strategy/MicroStrategy model.', photo:'69bc37821c4f113994d21633_6568f218c940cd2dbc453138.webp', priority:'med', pitch:['sto'], isNew:true},
  {jp:'デラル・イスリム', en:'Derar Islim', company:'Antalpha', role:'COO / CEO Americas & EMEA', cat:'金融サービス', catEn:'Financial Services', desc:'NASDAQ上場デジタル資産金融サービス大手AntalplhaのCOO。元Genesis暫定CEO。デリバティブと構造化クレジット専門。機関向けファイナンシングでSTOトークン・JPYR両方に関連。', descEn:'COO of Antalpha, a NASDAQ-listed digital asset financial services firm. Former interim CEO of Genesis. Derivatives and structured credit specialist. Relevant to both STO token and JPYR for institutional financing.', photo:'69777c5b7805a0ced0012d6e_6ssEg0zG1BaZ5feBnH1fpUblOPCjL0mEAs1DymCgK9k.webp', priority:'med', pitch:['sto','jpyr'], isNew:false},
  {jp:'アダム・リーズ', en:'Adam Reeds', company:'Ledn', role:'Co-Founder & CEO', cat:'レンディング', catEn:'Lending', desc:'Bitcoin担保レンディングプラットフォームLedn CEO。BTCを担保にドルを借りるサービス。JPYR統合（JPY建てレンディング）の文脈で会話が成立しやすい。', descEn:'CEO of Ledn, a Bitcoin-collateralized lending platform. Service for borrowing dollars against BTC. Natural conversation in the context of JPYR integration (JPY-denominated lending).', photo:'69bd4be908c8b63965981a5a_aMdINgnXgNiRhOEqfYDw0Mh_VAn3kX95hca82ilgtEs.webp', priority:'med', pitch:['jpyr'], isNew:true},
  {jp:'フランク・ホームズ', en:'Frank Holmes', company:'U.S. Global Investors', role:'CEO & CIO', cat:'投資家', catEn:'Investor', desc:'HIVE DigitalマイニングのExecutive Chairman兼任。米国有数のミューチュアルファンド運用会社経営。資産運用業界にBitcoin×STOトークンを紹介できる窓口。', descEn:'Also Executive Chairman of HIVE Digital Mining. Runs one of the top US mutual fund management companies. Gateway to introduce Bitcoin × STO token to the asset management industry.', photo:'6986923b3f9667ef9a3a1e6e_h4iJLxmgweq_rSb4ao_wIx4o5d91p_9M_23hoq1nazo.webp', priority:'med', pitch:['sto'], isNew:false},
  {jp:'ケイトリン・ロング', en:'Caitlin Long', company:'Custodia Bank', role:'Founder & CEO', cat:'銀行・規制', catEn:'Banking/Regulation', desc:'ワイオミング州初のBitcoinネイティブ銀行Custodia Bankの創業者。元モルガン・スタンレーMD。JPYRの銀行パートナーとして、規制準拠のルートを開ける可能性がある。', descEn:'Founder of Custodia Bank, Wyoming\'s first Bitcoin-native bank. Former Morgan Stanley MD. Could open a regulatory-compliant route as JPYR\'s banking partner.', photo:'69777c6360a6137841cbb53a_I0HdPYGnKCHTf6C7SyndMNmH-_nqZ6CGZee647KoK9Q.webp', priority:'med', pitch:['jpyr'], isNew:false},
  {jp:'ブレント・ジョンソン', en:'Brent Johnson', company:'Santiago Capital', role:'CEO', cat:'マクロ経済', catEn:'Macro Economics', desc:'「ドル・ミルクシェイク理論」の提唱者。高純資産ファミリー向け資産運用。「円安+日本の低金利×グローバルBTC投資」というR Inc.のメッセージと文脈が合いやすい。', descEn:'Proponent of the "Dollar Milkshake Theory". Asset management for high-net-worth families. R Inc.\'s message of "weak yen + Japan\'s low rates × global BTC investment" aligns well with his thesis.', photo:'6972a307e8c4e395e94eeb44_OOsQMA2QiwiAKE1DWh7HacwrGx0KK_R9hP4aC9I5chU.webp', priority:'med', pitch:['sto'], isNew:false},
  {jp:'チャールズ・エドワーズ', en:'Charles Edwards', company:'Capriole Investments', role:'Founder', cat:'投資・リサーチ', catEn:'Investment/Research', desc:'Hash Ribbons、Bitcoin Production Costなど著名なオンチェーン指標の開発者。体系的マクロ投資家。STOトークンのデータ裏付け・投資家候補として有望。', descEn:'Developer of well-known on-chain indicators like Hash Ribbons and Bitcoin Production Cost. Systematic macro investor. Promising as STO token data validation and investor candidate.', photo:null, priority:'med', pitch:['sto'], isNew:false},
  {jp:'アレックス・ソーン', en:'Alex Thorn', company:'Galaxy Digital', role:'MD & Research Head', cat:'リサーチ', catEn:'Research', desc:'デジタル資産大手Galaxy Digitalの全社リサーチ責任者。元Fidelity暗号資産VC。Galaxyは機関投資家向けデジタル資産ファイナンスの主要プレーヤー。STOトークンの機関パートナー候補。', descEn:'Head of Research at Galaxy Digital, a major digital asset firm. Former Fidelity crypto VC. Galaxy is a key player in institutional digital asset finance. Candidate as STO token institutional partner.', photo:'6986670e17d5ae83249abd9b_Q7cmAoznWlueWssdcxlPUz6NNrBGyjz2RJuimPEMDi8.webp', priority:'med', pitch:['sto'], isNew:false},
  {jp:'ファリャル・シラザード', en:'Faryar Shirzad', company:'Coinbase', role:'Chief Policy Officer', cat:'規制', catEn:'Regulation', desc:'CoinbaseのChief Policy Officer。元Goldman Sachs政策エグゼクティブ。米国のBTC規制動向を把握する上で重要なコンタクト。', descEn:'Coinbase\'s Chief Policy Officer. Former Goldman Sachs policy executive. Key contact for understanding US BTC regulatory trends.', photo:'699384ff6978b148a629de61_FiVJYeKKDt5w9fdp3A4F-A1mamr1a4k3a0dZo7jsvO0.webp', priority:'med', pitch:['net'], isNew:true},
  {jp:'マイルズ・スーター', en:'Miles Suter', company:'Block', role:'Bitcoin Product Lead', cat:'技術', catEn:'Technology', desc:'Jack DorseyのBlock（旧Square）のBitcoin製品責任者。Cash App経由でBitcoinを数千万人に提供。JPYR統合・IZAKAYAウォレット連携のパートナーとして話しやすい。', descEn:'Bitcoin Product Lead at Block (formerly Square) by Jack Dorsey. Delivers Bitcoin to tens of millions via Cash App. Easy partner to approach about JPYR integration and IZAKAYA wallet collaboration.', photo:'69b854a3184076ac4152248f_1488e2c43a0b2ffd85c102de.webp', priority:'med', pitch:['jpyr','izakaya'], isNew:true},
  {jp:'マーティ・ベント', en:'Marty Bent', company:'TFTC / Ten31', role:'Founder / Partner', cat:'メディア・投資', catEn:'Media/Investment', desc:'TFTCポッドキャスト（Bitcoin podcast）のFounder兼Bitcoin特化VCファンドTen31のパートナー。影響力あるBitcoinコミュニティのオピニオンリーダー。STOトークンの初期支持者に。', descEn:'Founder of TFTC podcast and partner at Bitcoin-focused VC fund Ten31. Influential opinion leader in the Bitcoin community. Potential early STO token supporter.', photo:'69777c306b0209f04bc95715_vS7kuBK0dhHFRy3Jnv7kn-cmIemXbXAJF0Nhae4s7KQ.webp', priority:'med', pitch:['sto'], isNew:true},
  {jp:'マット・オデル', en:'Matt Odell', company:'Ten31 / OpenSats', role:'Partner / CoFounder', cat:'投資', catEn:'Investment', desc:'Ten31（Bitcoin VC）とOpenSats（Bitcoin開発グラント）のCoFounder。Bitcoin最大主義者コミュニティの中心人物。', descEn:'CoFounder of Ten31 (Bitcoin VC) and OpenSats (Bitcoin dev grants). Central figure in the Bitcoin maximalist community.', photo:'6972a307e8c4e395e94eeb47_ilg_1tcj1y5zTWLsxmsy_O_Y1Fpvb1IykSXrlSA4WV8.webp', priority:'med', pitch:['sto'], isNew:true},
  {jp:'フレッド・ティール', en:'Fred Thiel', company:'MARA Holdings', role:'Chairman & CEO', cat:'マイニング', catEn:'Mining', desc:'NASDAQ上場の世界最大規模BTCマイニング企業MARAのトップ。4大陸15データセンター運営。ネットワーキングと業界情報収集に有用。', descEn:'Head of MARA, one of the world\'s largest publicly traded BTC mining companies (NASDAQ). Operates 15 data centers across 4 continents. Useful for networking and industry intel.', photo:'6980af8979a700e30de698b5_910b9291c5a0fbe14ebecba9.webp', priority:'med', pitch:['net'], isNew:false},
  {jp:'マット・シュルツ', en:'Matt Schultz', company:'CleanSpark', role:'CEO & Chairman', cat:'マイニング', catEn:'Mining', desc:'NASDAQ上場マイニング企業CleanSpark（CLSK）の共同創業者兼CEO。北米最大級マイナー。業界ネットワーキングに有用。', descEn:'Co-founder & CEO of CleanSpark (CLSK), a NASDAQ-listed mining company. One of the largest miners in North America. Useful for industry networking.', photo:'699863d61b051bb144034021_ee2016990fdf27bb1a70d960.webp', priority:'med', pitch:['net'], isNew:false},
  {jp:'デビッド・ベイリー', en:'David Bailey', company:'Nakamoto', role:'CEO & Chairman', cat:'経営者', catEn:'Executive', desc:'Bitcoin Magazineおよびビットコインカンファレンスの主催者。Nakamoto（旧BTC Inc）。このカンファレンス全体の顔。関係構築しておくと来年以降も有利。', descEn:'Organizer of Bitcoin Magazine and the Bitcoin conference. Nakamoto (formerly BTC Inc). The face of this entire conference. Building a relationship benefits future years.', photo:'698e06dd42bfa4d58902870b_ckWBXvvX8u_rGufCgvXe1LtYEkdiJ20dI3BBP4l1ETA.webp', priority:'med', pitch:['net'], isNew:false},
  {jp:'アイリーン・ガオ', en:'Irene Gao', company:'Bitmain', role:'President of Mining', cat:'マイニング', catEn:'Mining', desc:'世界最大のBitcoinマイニング機器メーカーBitmainのPresident of Mining。Bitmainは月間スポンサー（Moon tier）。業界でのブランド認知に有用。', descEn:'President of Mining at Bitmain, the world\'s largest Bitcoin mining equipment manufacturer. Bitmain is a Moon tier sponsor. Useful for brand recognition in the industry.', photo:'68fa74246d4060b0c4c6561c_682e12809ea6ac541e0fbe22_fKlkhwJR4GBZRHV8iWGuf3VxZjTod8LiTMVoBRFKzZE.webp', priority:'med', pitch:['net'], isNew:true},

  // ★ LOW PRIORITY
  {jp:'バーニー・モレノ', en:'Bernie Moreno', company:'U.S. Senate', role:'Senator', cat:'政治家', catEn:'Politician', desc:'オハイオ州選出の上院議員。クリプトフレンドリーな議員として知られ、銀行委員会でデジタル資産政策を推進。規制対応の文脈でネットワーキング価値あり。', descEn:'Ohio Senator known as a crypto-friendly legislator. Advancing digital asset policy on the Banking Committee. Valuable for regulatory networking.', photo:null, priority:'low', pitch:['net'], isNew:true},
  {jp:'アマンダ・ファビアーノ', en:'Amanda Fabiano', company:'Nakamoto Inc.', role:'COO', cat:'経営', catEn:'Executive', desc:'Nakamoto Inc.（Bitcoin Magazine親会社）のCOO。David Baileyの右腕として運営全般を統括。カンファレンス主催側との関係構築に有用。', descEn:'COO of Nakamoto Inc. (parent of Bitcoin Magazine). David Bailey\'s right hand, overseeing overall operations. Useful for building relationships with conference organizers.', photo:null, priority:'low', pitch:['net'], isNew:true},
  {jp:'アナイゼ・カニンバ', en:'Anaise Kanimba', company:'Africa Bitcoin Institute', role:'Founder & Executive Director', cat:'非営利', catEn:'Nonprofit', desc:'Africa Bitcoin Instituteの創業者兼事務局長。アフリカ地域でのBitcoin教育・普及を推進。グローバルネットワーキング。', descEn:'Founder & Executive Director of Africa Bitcoin Institute. Promoting Bitcoin education and adoption across Africa. Global networking.', photo:null, priority:'low', pitch:['net'], isNew:true},
  {jp:'アンドリュー・ビギン', en:'Andrew Begin', company:'Galoy', role:'Chief Strategy Officer', cat:'技術', catEn:'Technology', desc:'Bitcoin Banking OSプラットフォームGaloyのCSO。Lightning決済インフラ。IZAKAYAウォレットの技術連携候補。', descEn:'CSO of Galoy, a Bitcoin Banking OS platform. Lightning payment infrastructure. Candidate for IZAKAYA wallet technical integration.', photo:null, priority:'low', pitch:['izakaya'], isNew:true},
  {jp:'アレクサンドル・レゼ', en:'Alexandre Laizet', company:'Capital B', role:'Board Director of Bitcoin Strategy', cat:'投資', catEn:'Investment', desc:'Capital BのBitcoin戦略取締役。機関投資家向けBitcoin戦略を推進。STOトークン・JPYRの文脈でネットワーキング価値あり。', descEn:'Board Director of Bitcoin Strategy at Capital B. Promoting institutional Bitcoin strategy. Networking value in STO token and JPYR context.', photo:null, priority:'low', pitch:['sto'], isNew:true},
  {jp:'アリ・ターガー', en:'Ali Tager', company:'National Cryptocurrency Association', role:'VP, External Affairs', cat:'業界団体', catEn:'Industry Association', desc:'National Cryptocurrency AssociationのVP。業界ロビイング・規制対応の文脈でネットワーキング。', descEn:'VP of External Affairs at National Cryptocurrency Association. Networking for industry lobbying and regulatory engagement.', photo:null, priority:'low', pitch:['net'], isNew:true},
  {jp:'アレン・ヘルム', en:'Allen Helm', company:'BTC Inc.', role:'Director of Business Development, Treasuries', cat:'ビジネス開発', catEn:'Business Development', desc:'BTC Inc.の財務向け事業開発ディレクター。Bitcoin for Corporationsプログラムの担当。法人向けBTC戦略の文脈で有用。', descEn:'Director of BD for Treasuries at BTC Inc. Manages Bitcoin for Corporations program. Useful in corporate BTC strategy context.', photo:null, priority:'low', pitch:['net'], isNew:true},
  {jp:'アフロマン', en:'Afroman', company:'(Independent)', role:'Rapper / Cultural Speaker', cat:'エンターテインメント', catEn:'Entertainment', desc:'グラミーノミネートのラッパー。Bitcoin 2026カルチャー枠のスピーカー。ブース集客・SNS映えに活用。', descEn:'Grammy-nominated rapper. Cultural speaker at Bitcoin 2026. Useful for booth traffic and social media engagement.', photo:null, priority:'low', pitch:['media'], isNew:true},
  {jp:'ポール・アトキンス', en:'Paul Atkins', company:'SEC', role:'Chairman', cat:'規制当局', catEn:'Regulator', desc:'トランプ大統領が指名した第34代SEC議長。クリプトフレンドリーな規制当局トップ。直接営業は難しいが、挨拶・名刺交換でコンプライアンス文脈を得られる。', descEn:'34th SEC Chairman nominated by President Trump. Crypto-friendly regulatory leader. Hard to do direct sales, but a greeting and card exchange provides compliance context.', photo:'6972a307e8c4e395e94eeb3e_2BzOTwTGF_fgb-5GSlEDzb9jrPlqtD4jYf_QK-9iMHI.webp', priority:'low', pitch:['net'], isNew:false},
  {jp:'マイク・セリグ', en:'Mike Selig', company:'CFTC', role:'Chairman', cat:'規制当局', catEn:'Regulator', desc:'2025年12月就任の第16代CFTC議長。前SEC暗号資産タスクフォースの主任顧問。デジタル資産規制の整合化を主導中。', descEn:'16th CFTC Chairman, took office December 2025. Former SEC crypto task force chief counsel. Leading harmonization of digital asset regulation.', photo:'6972a311ea31b2d42d6a99e8_DBuk5h4LfBOwRTGddYSvuMUK_zC0GSwDzYx0-cz1K24.webp', priority:'low', pitch:['net'], isNew:false},
  {jp:'シンシア・ラミス', en:'Cynthia Lummis', company:'U.S. Senate', role:'Senator', cat:'政治家', catEn:'Politician', desc:'「クリプト・クイーン」の異名を持つワイオミング州選出上院議員。BITCOIN法（米国戦略的BTC備蓄法案）の発案者。', descEn:'Wyoming Senator known as the "Crypto Queen". Originator of the BITCOIN Act (US strategic BTC reserve bill).', photo:'69a99c8c09404f6a5e4965dc_3oWm6lqlCM3ZI7GxiMbOUfL9VKWVxLeE8iFkiDitm4s.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'パトリック・ウィット', en:'Patrick Witt', company:'White House', role:'Executive Director', cat:'政治家', catEn:'Politician', desc:'ホワイトハウスのデジタル資産政策の司令塔。国防省の戦略投資ディレクターも兼務。元McKinsey、Yale・Harvard Law卒。', descEn:'White House digital asset policy lead. Also serves as DoD strategic investment director. Former McKinsey, Yale & Harvard Law graduate.', photo:'698692286880c8ce813a5a6f_NvL4tTC1CTNWD4uR_dMSMmQWIpoKhVw6N-3MJf7-VNg.webp', priority:'low', pitch:['net'], isNew:false},
  {jp:'エリック・トランプ', en:'Eric Trump', company:'American Bitcoin', role:'Co-Founder & CSO', cat:'ビジネス', catEn:'Business', desc:'トランプ大統領の息子。American Bitcoin（Trump familyのBTCマイニング会社）のCSO。政治的コネクション・ブランド価値あり。直接営業よりも写真・名刺目的。', descEn:'Son of President Trump. CSO of American Bitcoin (Trump family BTC mining company). Political connections and brand value. More for photo ops and card exchange than direct sales.', photo:'69b83acd266d2ccdabb89e84_44FTlA0VDvDlDULs59HExjSO2UMsRCyJg7FXIDPg1oU.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'アダム・バック', en:'Adam Back', company:'Blockstream', role:'Co-founder & CEO', cat:'技術', catEn:'Technology', desc:'Hashcash発明者（ビットコインホワイトペーパーに引用）、cypherpunk。BlockstreamのCEO。Bitcoin技術の生き字引き。技術的信頼性のある対話が可能。', descEn:'Inventor of Hashcash (cited in the Bitcoin whitepaper), cypherpunk. CEO of Blockstream. A living encyclopedia of Bitcoin technology. Enables credible technical dialogue.', photo:'69aece97fa06c6812bb21e7d_2a3f52ac959f63abd103a7df.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'ナタリー・ブルネル', en:'Natalie Brunell', company:'Talking Bitcoin', role:'Host & Author', cat:'メディア', catEn:'Media', desc:'世界No.1 Bitcoinポッドキャスト「Coin Stories」のホスト兼著者。元エミー賞受賞テレビジャーナリスト。メディア露出機会としてアプローチ可。', descEn:'Host & author of "Coin Stories", the world\'s #1 Bitcoin podcast. Former Emmy Award-winning TV journalist. Approachable for media exposure opportunities.', photo:'69820d7160b998d29b041a33_f99e2d24f75200d47a3c7e11.webp', priority:'low', pitch:['media'], isNew:false},
  {jp:'ピーター・マコーマック', en:'Peter McCormack', company:'Real Bedford FC', role:'Chairman', cat:'メディア', catEn:'Media', desc:'Bitcoinポッドキャスト「What Bitcoin Did」のホスト。英国Real Bedford FCのオーナー会長。BTCで運営するサッカークラブで話題。メディア露出機会。', descEn:'Host of Bitcoin podcast "What Bitcoin Did". Owner-chairman of Real Bedford FC in England. Known for running a football club on BTC. Media exposure opportunity.', photo:'6972a311ea31b2d42d6a99e5_lh-z6TQpvKYEhqjELVy2FZhpkEmqgQkxnrS9a63b_6o.webp', priority:'low', pitch:['media'], isNew:false},
  {jp:'アーロン・アーノルド', en:'Aaron Arnold', company:'Altcoin Daily', role:'Host & Founder', cat:'メディア', catEn:'Media', desc:'登録者数300万人超のYouTubeチャンネル「Altcoin Daily」共同創業者。Bitcoin・クリプトニュースを日次で発信。メディア露出狙いでアプローチ。', descEn:'Co-founder of "Altcoin Daily" YouTube channel with 3M+ subscribers. Daily Bitcoin & crypto news. Approach for media exposure.', photo:'698666eec4f9fac2157c9f5f_QOqbVzixxWbrBDmOW30jGOKqxO2cCKL5A7dccFjIyFc.webp', priority:'low', pitch:['media'], isNew:false},
  {jp:'ポール・グリウォール', en:'Paul Grewal', company:'Coinbase', role:'Chief Legal Officer', cat:'法律', catEn:'Legal', desc:'CoinbaseのCLO、元連邦裁判所判事。デジタル資産の法務・コンプライアンスの第一人者。STO規制対応の参考情報を得るための会話相手として有用。', descEn:'Coinbase CLO, former federal judge. Leading authority on digital asset legal & compliance. Useful conversation partner for STO regulatory insights.', photo:'699384d7f536c91a926380d7_mvyb2_RW65b8-ghGrYwbtCPxiTjjSwemCJq9riRSS4w.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'アレックス・グラッドスタイン', en:'Alex Gladstein', company:'Human Rights Foundation', role:'CSO', cat:'人権', catEn:'Human Rights', desc:'HRFのCSO。Bitcoin for Human Rightsを世界的に推進。権威主義国家での自由通貨としてのBTC。', descEn:'CSO of HRF. Globally promotes Bitcoin for Human Rights. Advocates BTC as freedom currency in authoritarian states.', photo:'6980af2e38cd1cd842eb6671_LCLwdK6EBhq8kkg3XWJlgHo3k6YeXXXV7Peb_RFmA9I.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'カーティス・ヤービン', en:'Curtis Yarvin', company:'Urban Tiger', role:'CEO', cat:'思想家・哲学者', catEn:'Thinker/Philosopher', desc:'Bitcoinの経済学を最初に説明した思想家の一人と自称。2014年のストア・オブ・バリュー評価へのシフトを主導。ネットワーキング目的。', descEn:'Self-described as one of the first thinkers to explain Bitcoin economics. Led the shift to store-of-value evaluation in 2014. Networking purpose.', photo:'69aae1d6a9d43dd5a54fca28_QK9IZZoWyw48HV6_UbksDEllbTSAjh2dJ0jAmjaRap0.webp', priority:'low', pitch:['net'], isNew:false},
  {jp:'ダニエル・ディマルティノ・ブース', en:'Danielle DiMartino Booth', company:'QI Research', role:'CEO & Chief Strategist', cat:'マクロ経済', catEn:'Macro Economics', desc:'元ダラス連銀アドバイザーの独立マクロアナリスト。FRB批判の著書で知られる金融メディアの常連コメンテーター。', descEn:'Independent macro analyst, former Dallas Fed advisor. Known for Fed-critical authorship. Regular commentator on financial media.', photo:'699f501b7ecef12fbb71cd00_AzZe56kueLpbEJxJNvpDACzMMafJBjK3bNhr577lGHk.webp', priority:'low', pitch:['net'], isNew:false},
  {jp:'アレックス・フォン・フランケンベルク', en:'Alex von Frankenberg', company:'HTGF', role:'Author & Investor', cat:'投資家', catEn:'Investor', desc:'2000年からハイテクスタートアップへの初期投資を行うドイツ人投資家。著書『Bitcoin – The Honest Money』を執筆。欧州からのSTOトークン投資家候補。', descEn:'German investor in high-tech startups since 2000. Author of "Bitcoin \u2013 The Honest Money". European STO token investor candidate.', photo:'695fdf59d7a0eefaa87723b7_445bb3e4729838ccb83a92d2.webp', priority:'low', pitch:['sto'], isNew:false},
  {jp:'アレシュ・ミフル', en:'Aleš Michl', company:'Czech National Bank', role:'Governor', cat:'規制当局', catEn:'Regulator', desc:'チェコ国立銀行総裁。欧州で最もBTCフレンドリーな中央銀行幹部の一人。中央銀行レベルでのBTC認知広がりの文脈で有用。', descEn:'Governor of the Czech National Bank. One of Europe\'s most BTC-friendly central bank officials. Useful in the context of central bank-level BTC awareness.', photo:'696027c4e36d599b44d19ffd_YtIfyi29GWpPwxfKmET7cG8qejUJVHu8GGlh5o53Fwc.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'ヨルグ・グイド・ヒュルスマン', en:'Jörg Guido Hülsmann', company:'アンジェ大学', role:'経済学教授', cat:'学術', catEn:'Academia', desc:'ミーゼス研究所シニアフェロー。オーストリア学派の経済学者。貨幣と銀行理論の第一人者で『The Ethics of Money Production』著者。', descEn:'Mises Institute Senior Fellow. Austrian school economist. Leading authority on money and banking theory, author of "The Ethics of Money Production".', photo:null, priority:'low', pitch:['net'], isNew:false},
  {jp:'ロベルト・リオス', en:'Roberto Rios', company:'Lima Research LLC', role:'Founder', cat:'リサーチ', catEn:'Research', desc:'マクロライター・前Carta Fintechアナリスト。Bitcoin及びマクロ経済に関するリサーチを発信。ネットワーキング目的。', descEn:'Macro writer, former Carta Fintech analyst. Publishes research on Bitcoin and macro economics. Networking purpose.', photo:null, priority:'low', pitch:['net'], isNew:false},
  {jp:'ケン・フローリアン', en:'Kenny Florian', company:'Florian Martial Arts', role:'Owner', cat:'セレブリティ', catEn:'Celebrity', desc:'UFC3回タイトル挑戦者、ブラジリアン柔術5段黒帯。Bitcoin collab as celebrity。Ankaポッドキャストのホスト。写真撮影・SNS目的に。', descEn:'3x UFC title challenger, 5th-degree BJJ black belt. Bitcoin collab as celebrity. Host of the Anka podcast. For photo ops and social media.', photo:'69869232dd3d4d30fb9ff359_e06219b4fe11c2116d51318b.webp', priority:'low', pitch:['media'], isNew:false},
  {jp:'アーロン・バーネット', en:'Aaron Burnett', company:'Mach33 Financial Group', role:'CEO', cat:'金融', catEn:'Finance', desc:'Mach33 Financial Group CEO。Bitcoin focused financial services.', descEn:'CEO of Mach33 Financial Group. Bitcoin-focused financial services.', photo:'6993850482a113ae43e743f5_3RepGM134pIzEpRX2Zj3hPff75rMOWbnE--QPBCNpJk.webp', priority:'low', pitch:['sto'], isNew:true},
  {jp:'アーロン・ダニエル', en:'Aaron Daniel', company:'Resolvr', role:'Co-founder', cat:'金融', catEn:'Finance', desc:'Bitcoin-native lending/financial services platform Resolvr の共同創業者。', descEn:'Co-founder of Resolvr, a Bitcoin-native lending and financial services platform.', photo:'69444250c28c1a7c8a73c621_2b032ab824d8fb7ffea3bf50.webp', priority:'low', pitch:['jpyr'], isNew:true},
  {jp:'アーロン・ジン', en:'Aaron Ginn', company:'Hydra Host', role:'CEO & Co-Founder', cat:'AI・コンピューティング', catEn:'AI/Computing', desc:'AI学習・推論向け高性能GPUインフラ企業Hydra HostのCEO。マイニング事業者のAI転換を支援。', descEn:'CEO of Hydra Host, a high-performance GPU infrastructure company for AI training and inference. Supports miners transitioning to AI.', photo:'69bd9872918a6d047163174d_6SZdHhdWT_KeHjH8Hw-JYqQVLxzOfRp6mhxuAdmP_CU.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'アーロン・ファン・ワーダム', en:'Aaron van Wirdum', company:'Bitcoin Magazine', role:'Technical Editor', cat:'メディア', catEn:'Media', desc:'Bitcoin Magazineのテクニカルエディター。Bitcoin技術の深い専門知識を持つジャーナリスト。メディア露出・技術的コンタクトとして有用。', descEn:'Technical Editor at Bitcoin Magazine. Journalist with deep Bitcoin technical expertise. Useful as media exposure and technical contact.', photo:'6944148d9ba1b24cc035f2a2_c168918269dc46e2888d8690.webp', priority:'low', pitch:['media'], isNew:true},
  {jp:'アレッサンドロ・チェチェーレ', en:'Alessandro Cecere', company:'El Dorado / Luxor', role:'CMO & Co-Founder', cat:'マイニング', catEn:'Mining', desc:'ベネズエラ出身のBitcoin伝道師。ラテンアメリカ初のBitcoin衛星接続を実現。El DoradoのCMO＆共同創業者（中南米ステーブルコインアプリ）。', descEn:'Venezuelan-born Bitcoin evangelist. Achieved Latin America\'s first Bitcoin satellite connection. CMO & Co-founder of El Dorado (LatAm stablecoin app).', photo:'69a1dbeb4c451d86a5100bdf_PZDbpvI8pDP7JwoChPc3htwntUA6H9JRoMO5yFrDwGA.webp', priority:'low', pitch:['net'], isNew:false},
  {jp:'アレクサンダー・ロズベン', en:'Alexander Lozben', company:'Interhash', role:'Founder & CEO', cat:'マイニング', catEn:'Mining', desc:'Interhash CEO。Bitcoin mining operations.', descEn:'CEO of Interhash. Bitcoin mining operations.', photo:'69ba015be27d9cb8bcfc6edb_NLc1TDI8EDYAVCjUoq9Cx-cFPUWZhHQAjrMkpB_3IlM.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'アレックス・ルーィン', en:'Alex Lewin', company:'Fedi', role:'Software Engineer', cat:'技術', catEn:'Technology', desc:'Fedi（Bitcoin/Lightningコミュニティカストディプラットフォーム）のエンジニア。IZAKAYAウォレット技術連携の文脈で話せる相手。', descEn:'Software Engineer at Fedi, a Bitcoin/Lightning community custody platform. Good counterpart for IZAKAYA wallet technical integration discussions.', photo:'695bd71e9bf6d9ecd4df5056_c2262e76d863042a652ff9da.webp', priority:'low', pitch:['izakaya'], isNew:true},
  {jp:'アレックス・プルーデン', en:'Alex Pruden', company:'Project Eleven', role:'Co-Founder & CEO', cat:'量子コンピューティング', catEn:'Quantum Computing', desc:'Bitcoin量子コンピューティング耐性研究のProject Eleven Co-founder & CEO。将来のBitcoinセキュリティ技術の最前線。ネットワーキング。', descEn:'Co-Founder & CEO of Project Eleven, researching Bitcoin quantum computing resistance. At the forefront of future Bitcoin security technology. Networking.', photo:'69bd4e509d7f1d43a149a9fb_32beb2b3cedff59ea6cd5f42.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'アダム・サンダース', en:'Adam Saunders', company:'Columbia Center', role:'Co-Founder', cat:'農業・研究', catEn:'Agriculture/Research', desc:'Columbia Center for Urban Agricultureの共同創業者。ユニークな分野からのBitcoin参加者。', descEn:'Co-Founder of Columbia Center for Urban Agriculture. A unique cross-sector Bitcoin participant.', photo:'694442617269f8d1975579dc_t7dVzEQj8__igH4NU_rM5ruln_DQJRYZozP99IXZvhg.webp', priority:'low', pitch:['net'], isNew:true},
  {jp:'アレックス・シェーファー', en:'Alex Schaefer', company:'(Independent)', role:'Artist', cat:'アート', catEn:'Art', desc:'燃える銀行を描くBitcoinアーティスト。Bitcoinカルチャーの象徴的人物。ブース集客・SNS映えのために関係構築も有効。', descEn:'Bitcoin artist known for painting burning banks. Iconic figure in Bitcoin culture. Useful for booth traffic and social media engagement.', photo:'69a1dbfe190a3e92cdab0305_b4c20cb26bbc5f4658441c48.webp', priority:'low', pitch:['media'], isNew:true},
];

const sponsors = {
  moon: [
    {name:'Antalpha', url:'https://www.antalpha.com', cat:'フィンテック', catEn:'Fintech', desc:'NASDAQ上場(ANTA)、デジタル資産業界向けファイナンシング・テクノロジー・リスク管理', descEn:'NASDAQ-listed (ANTA). Financing, technology, and risk management for the digital asset industry.', pitch:['sto','jpyr'], isNew:false},
    {name:'Bitmain', url:'https://www.bitmain.com/', cat:'マイニング機器', catEn:'Mining Equipment', desc:'世界最大のデジタル通貨マイニングサーバーメーカー、ANTMINER', descEn:'World\'s largest digital currency mining server manufacturer. ANTMINER series.', pitch:['net'], isNew:false},
    {name:'Block', url:'https://block.xyz/bitcoin', cat:'エコシステム', catEn:'Ecosystem', desc:'Bitcoinのエンドツーエンドエコシステム。Cash App、Bitkey、Spiralを傘下に持つ。', descEn:'End-to-end Bitcoin ecosystem. Includes Cash App, Bitkey, and Spiral.', pitch:['jpyr','izakaya'], isNew:false},
    {name:'CleanSpark', url:'https://www.cleanspark.com/', cat:'マイニング', catEn:'Mining', desc:'NASDAQ上場(CLSK)、米国最大のBitcoinマイナー、低炭素電力使用', descEn:'NASDAQ-listed (CLSK). Largest US Bitcoin miner using low-carbon energy.', pitch:['net'], isNew:false},
    {name:'Frax', url:'https://frax.com/frxbtc', cat:'DeFi・ステーブルコイン', catEn:'DeFi/Stablecoin', desc:'GENIUS準拠ステーブルコインFRXUSD発行、BTCレバレッジ・利回りDeFiプロトコル', descEn:'GENIUS-compliant stablecoin FRXUSD issuer. BTC leverage and yield DeFi protocol.', pitch:['izakaya'], isNew:false},
    {name:'Gemini', url:'https://www.gemini.com/', cat:'取引所', catEn:'Exchange', desc:'Winklevoss兄弟が2014年創業の暗号資産取引所。JPYR上場候補として最優先。', descEn:'Crypto exchange founded by Winklevoss twins in 2014. Top priority candidate for JPYR listing.', pitch:['jpyr'], isNew:false},
    {name:'MARA', url:'https://www.mara.com', cat:'マイニング', catEn:'Mining', desc:'NASDAQ上場(MARA)、デジタル資産コンピューティングのグローバルリーダー', descEn:'NASDAQ-listed (MARA). Global leader in digital asset computing.', pitch:['net'], isNew:false},
    {name:'Metaplanet', url:'https://metaplanet.jp/', cat:'BTC保有企業', catEn:'BTC Treasury', desc:'🆕 東証上場の日本版MicroStrategy。大量BTC保有企業。Simon GerovichがスピーカーかつMoonスポンサー。日本語でアプローチ可能な最重要コンタクト。', descEn:'TSE-listed, Japan\'s MicroStrategy with massive BTC holdings. Simon Gerovich is both speaker and Moon sponsor. Top contact approachable in Japanese.', pitch:['jpyr','sto'], isNew:true},
    {name:'Nakamoto', url:'https://nakamoto.com', cat:'メディア・経営', catEn:'Media/Business', desc:'🆕 David Bailey（カンファレンス主催者）のBitcoin企業。Bitcoin Magazine親会社。主催者とのリレーション構築。', descEn:'David Bailey\'s (conference organizer) Bitcoin company. Parent of Bitcoin Magazine. Build organizer relationship.', pitch:['net'], isNew:true},
    {name:'Robinhood', url:'https://robinhood.com', cat:'リテール投資', catEn:'Retail Investment', desc:'🆕 米国最大のリテール投資アプリ。2億人以上のユーザー、Bitcoin取引可能。JPYR上場・リテール展開の文脈で最重要取引所候補。', descEn:'Largest US retail investment app with 200M+ users. Bitcoin trading available. Top exchange candidate for JPYR listing and retail expansion.', pitch:['jpyr'], isNew:true},
  ],
  block3: [
    {name:'American Bitcoin', url:'https://americanbitcoin.com', cat:'マイニング', catEn:'Mining', desc:'🆕 Eric Trumpが関与するBitcoinマイニング企業。トランプ政権とのコネクション。', descEn:'Bitcoin mining company involving Eric Trump. Connection to the Trump administration.', pitch:['net'], isNew:true},
    {name:'BitGo', url:'https://bitgo.com', cat:'カストディ', catEn:'Custody', desc:'NYSE上場(BTGO)、デジタル資産インフラ、カストディ・ウォレット・ステーキング等。STOトークンの機関カストディ候補。', descEn:'NYSE-listed (BTGO). Digital asset infrastructure: custody, wallets, staking. Candidate for STO token institutional custody.', pitch:['sto','jpyr'], isNew:false},
    {name:'Cake Wallet', url:'https://cakewallet.com', cat:'ウォレット', catEn:'Wallet', desc:'使いやすさ重視の暗号資産ウォレット、プライバシー機能。IZAKAYA連携候補。', descEn:'User-friendly crypto wallet with privacy features. IZAKAYA integration candidate.', pitch:['izakaya'], isNew:false},
    {name:'Crypto.com', url:'https://crypto.com', cat:'取引所', catEn:'Exchange', desc:'1.5億人以上のユーザーを持つ大手暗号資産プラットフォーム。JPYR上場の主要候補。', descEn:'Major crypto platform with 150M+ users. Key candidate for JPYR listing.', pitch:['jpyr'], isNew:false},
    {name:'Human Rights Foundation', url:'https://hrf.org', cat:'非営利・人権', catEn:'Nonprofit/Human Rights', desc:'グローバルな人権促進・保護NPO、Bitcoin開発基金運営', descEn:'Global human rights promotion and protection NPO. Operates Bitcoin Development Fund.', pitch:['net'], isNew:false},
    {name:'Intelliflex', url:'https://www.intelliflex.io', cat:'データセンター冷却', catEn:'Data Center Cooling', desc:'カナダ製イマージョンマイニングデータセンター', descEn:'Canadian-made immersion mining data center solutions.', pitch:['net'], isNew:false},
    {name:'Kraken Institutional', url:'https://kraken.com', cat:'取引所', catEn:'Exchange', desc:'🆕 Krakens機関投資家向け部門。Dave Ripleyがco-CEO（スピーカー）。JPYR上場の最優先候補。', descEn:'Kraken\'s institutional division. Dave Ripley is co-CEO (speaker). Top priority candidate for JPYR listing.', pitch:['jpyr'], isNew:true},
    {name:'Qastle Wallet', url:'https://qastle.com', cat:'ウォレット', catEn:'Wallet', desc:'🆕 Bitcoin wallet。IZAKAYA連携検討候補。', descEn:'Bitcoin wallet. IZAKAYA integration candidate.', pitch:['izakaya'], isNew:true},
    {name:'Reed Smith', url:'https://www.reedsmith.com', cat:'法律', catEn:'Legal', desc:'🆕 グローバル法律事務所。デジタル資産部門あり。STO法務の参考コンタクト。', descEn:'Global law firm with digital asset practice. Reference contact for STO legal matters.', pitch:['net'], isNew:true},
    {name:'Riot Platforms', url:'https://www.riotplatforms.com', cat:'マイニング', catEn:'Mining', desc:'🆕 NASDAQ上場（RIOT）のBitcoinマイニング大企業。業界ネットワーキング。', descEn:'NASDAQ-listed (RIOT) major Bitcoin mining company. Industry networking.', pitch:['net'], isNew:true},
    {name:'SALT Lending', url:'https://saltlending.com', cat:'レンディング', catEn:'Lending', desc:'🆕 暗号資産担保ローンプラットフォーム。JPYR担保ローンの将来的な文脈で有用。', descEn:'Crypto-collateralized loan platform. Useful in the context of future JPYR-backed loans.', pitch:['jpyr'], isNew:true},
    {name:'Two Prime', url:'https://twoprime.io', cat:'投資', catEn:'Investment', desc:'🆕 Bitcoin focused investment fund。Alexander Blume CEO（スピーカー）。STOトークンのファンドパートナー候補。', descEn:'Bitcoin-focused investment fund. Alexander Blume CEO (speaker). Candidate as STO token fund partner.', pitch:['sto'], isNew:true},
    {name:'Unchained', url:'https://unchained.com', cat:'金融サービス', catEn:'Financial Services', desc:'🆕 Bitcoin-native金融サービス、マルチシグカストディ。JPYR・STO文脈で有用。', descEn:'Bitcoin-native financial services and multisig custody. Useful in JPYR and STO context.', pitch:['jpyr','sto'], isNew:true},
    {name:'Y Whales', url:'#', cat:'コミュニティ', catEn:'Community', desc:'🆕 Bitcoin Whaleコミュニティ。高額投資家ネットワーキング。', descEn:'Bitcoin Whale community. High-value investor networking.', pitch:['sto'], isNew:true},
  ],
  block2: [
    {name:'Bitdeer', url:'https://www.bitdeer.com/', cat:'マイニング', catEn:'Mining', desc:'世界有数のBitcoinマイニングサービスプロバイダー', descEn:'One of the world\'s leading Bitcoin mining service providers.', pitch:['net'], isNew:false},
    {name:'Blockware Solutions', url:'https://www.blockwaresolutions.com/', cat:'マイニング', catEn:'Mining', desc:'2017年創業、200MW超のホスト実績', descEn:'Founded 2017. 200MW+ hosting track record.', pitch:['net'], isNew:false},
    {name:'Calamos', url:'https://www.calamos.com', cat:'金融・資産運用', catEn:'Finance/Asset Management', desc:'🆕 老舗投資会社。Bitcoin ETFオプション戦略商品を提供。STOトークンの機関投資家層へのアプローチ窓口。', descEn:'Established investment firm offering Bitcoin ETF options strategy products. Gateway to institutional investors for STO token.', pitch:['sto'], isNew:true},
    {name:'Cohen & Company', url:'#', cat:'金融サービス', catEn:'Financial Services', desc:'🆕 金融サービス会社。デジタル資産部門あり。', descEn:'Financial services firm with digital asset division.', pitch:['sto'], isNew:true},
    {name:'eToro', url:'https://www.etoro.com', cat:'取引所・ソーシャル', catEn:'Exchange/Social Trading', desc:'世界最大のソーシャルトレーディングネットワーク。JPYR上場候補。', descEn:'World\'s largest social trading network. JPYR listing candidate.', pitch:['jpyr'], isNew:false},
    {name:'Layer Two Labs', url:'#', cat:'Bitcoin L2', catEn:'Bitcoin L2', desc:'🆕 Bitcoin L2（drivechains）の開発会社。IZAKAYAウォレットのL2統合候補。', descEn:'Bitcoin L2 (drivechains) development company. IZAKAYA wallet L2 integration candidate.', pitch:['izakaya'], isNew:true},
    {name:'Ledn', url:'https://ledn.io', cat:'レンディング', catEn:'Lending', desc:'🆕 Bitcoin担保レンディングプラットフォーム。Adam Reeds CEOはスピーカー。JPYR統合の文脈で有用。', descEn:'Bitcoin-collateralized lending platform. Adam Reeds CEO is a speaker. Useful for JPYR integration context.', pitch:['jpyr'], isNew:true},
    {name:'Meanwhile', url:'#', cat:'保険', catEn:'Insurance', desc:'🆕 Bitcoin建て生命保険。ユニークなBitcoin金融商品。ネットワーキング。', descEn:'Bitcoin-denominated life insurance. Unique Bitcoin financial product. Networking.', pitch:['net'], isNew:true},
    {name:'Whatsminer', url:'https://whatsminer.com', cat:'マイニング機器', catEn:'Mining Equipment', desc:'🆕 MicroBT製Whatsminerシリーズ。BitmainのANTMINERと競合する世界2位のマイニング機器メーカー。', descEn:'MicroBT\'s Whatsminer series. World\'s #2 mining equipment maker, competing with Bitmain\'s ANTMINER.', pitch:['net'], isNew:true},
    {name:'Polymarket', url:'https://polymarket.com', cat:'予測市場', catEn:'Prediction Market', desc:'🆕 分散型予測市場プラットフォーム。Bitcoin上での予測市場。IZAKAYAウォレット連携候補。', descEn:'Decentralized prediction market platform. Bitcoin-based prediction markets. IZAKAYA wallet integration candidate.', pitch:['izakaya'], isNew:true},
    {name:'Stand With Crypto', url:'#', cat:'政治活動', catEn:'Political Advocacy', desc:'🆕 Coinbase主導のクリプト支持政治活動団体。規制対応の文脈で有用。', descEn:'Coinbase-led crypto advocacy organization. Useful in regulatory context.', pitch:['net'], isNew:true},
    {name:'Syz Capital', url:'https://syz.com', cat:'資産運用', catEn:'Asset Management', desc:'🆕 スイスの資産運用会社。欧州機関投資家へのSTOトークン紹介窓口として有望。', descEn:'Swiss asset management firm. Promising gateway to European institutional investors for STO token.', pitch:['sto'], isNew:true},
    {name:'Travala', url:'https://www.travala.com', cat:'旅行・決済', catEn:'Travel/Payments', desc:'🆕 Bitcoin対応トラベルブッキングプラットフォーム。JPYR決済統合の文脈で話せる。', descEn:'Bitcoin-enabled travel booking platform. Relevant for JPYR payment integration discussions.', pitch:['jpyr'], isNew:true},
    {name:'VanEck', url:'https://www.vaneck.com', cat:'資産運用', catEn:'Asset Management', desc:'🆕 大手資産運用会社。Bitcoin ETF保有。運用資産800億ドル超。STOトークンの機関投資家パートナーとして最重要候補。', descEn:'Major asset manager with Bitcoin ETF. $80B+ AUM. Top candidate as STO token institutional partner.', pitch:['sto'], isNew:true},
    {name:'Yieldz', url:'#', cat:'利回り', catEn:'Yield', desc:'🆕 Bitcoin yield platform。IZAKAYAウォレット利回り統合候補。', descEn:'Bitcoin yield platform. IZAKAYA wallet yield integration candidate.', pitch:['izakaya'], isNew:true},
    {name:'GOWD', url:'https://gowd.com/', cat:'フィンテック', catEn:'Fintech', desc:'Bitcoin・ゲーマー・暗号資産投資家向け暗号資産フレンドリー金融機関', descEn:'Crypto-friendly financial institution for Bitcoin users, gamers, and crypto investors.', pitch:['jpyr'], isNew:false},
    {name:'HashHouse', url:'http://www.hashhouse.tech', cat:'マイニング・液冷', catEn:'Mining/Liquid Cooling', desc:'暗号資産マイニングと液冷ソリューション、ターンキーソリューション提供', descEn:'Crypto mining and liquid cooling solutions. Turnkey solutions provider.', pitch:['net'], isNew:false},
    {name:'Hydra Host', url:'https://hydrahost.com', cat:'AIコンピューティング', catEn:'AI Computing', desc:'AI学習・推論向け高性能GPUインフラ、マイニング事業者のAI転換支援', descEn:'High-performance GPU infrastructure for AI training and inference. Supports miners transitioning to AI.', pitch:['net'], isNew:false},
    {name:'Data Airflow', url:'https://dataairflow.com/', cat:'データセンター設備', catEn:'Data Center Equipment', desc:'データセンター向け換気・冷却システムの工学ソリューション', descEn:'Engineering solutions for data center ventilation and cooling systems.', pitch:['net'], isNew:false},
    {name:'FBOX', url:'https://www.fbox.tech/index', cat:'データセンター冷却', catEn:'Data Center Cooling', desc:'液冷・ハイドロ・空冷技術を専門とするデータセンター冷却ソリューション', descEn:'Data center cooling solutions specializing in liquid, hydro, and air cooling technologies.', pitch:['net'], isNew:false},
    {name:'BrainSprout Studios', url:'https://brainsproutstudios.com/', cat:'メディア・コンテンツ', catEn:'Media/Content', desc:'Bitcoinをテーマにした映像IP「Brucie Bitcoin™」を制作するクリエイティブスタジオ', descEn:'Creative studio producing Bitcoin-themed video IP "Brucie Bitcoin\u2122".', pitch:['media'], isNew:false},
  ],
  block1: [
    {name:'a16z crypto', url:'https://a16zcrypto.com/', cat:'VC・投資', catEn:'VC/Investment', desc:'Bitcoinおよびweb3スタートアップへの投資ファンド。STOトークンの有名名称活用の文脈でコンタクト価値あり。', descEn:'Investment fund for Bitcoin and web3 startups. Contact value for leveraging the a16z brand with STO token.', pitch:['sto'], isNew:false},
    {name:'Amplify ETFs', url:'https://amplifyetfs.com/', cat:'金融・ETF', catEn:'Finance/ETF', desc:'運用資産210億ドル超のETF、デジタル資産ETFを提供', descEn:'ETF provider with $21B+ AUM. Offers digital asset ETFs.', pitch:['sto'], isNew:false},
    {name:'Arch Lending', url:'https://archlending.com/', cat:'レンディング', catEn:'Lending', desc:'暗号資産担保ローン、米国規制ライセンス取得済み', descEn:'Crypto-collateralized loans. US regulatory licensed.', pitch:['jpyr'], isNew:false},
    {name:'Avalon Labs', url:'https://www.avalonfinance.xyz/', cat:'DeFi', catEn:'DeFi', desc:'Bitcoin担保ステーブルコイン世界最大の発行体、BTCファイナンシャルハブ', descEn:'World\'s largest issuer of Bitcoin-collateralized stablecoins. BTC financial hub.', pitch:['izakaya'], isNew:false},
    {name:'Aven', url:'https://aven.com/', cat:'フィンテック', catEn:'Fintech', desc:'AI・自動化による機械バンキングプラットフォーム、Bitcoin Card提供', descEn:'AI-powered automated banking platform. Offers Bitcoin Card.', pitch:['jpyr'], isNew:false},
    {name:'BinanceUS', url:'https://binance.us', cat:'取引所', catEn:'Exchange', desc:'米国ベースの暗号資産取引所。JPYR上場候補。', descEn:'US-based crypto exchange. JPYR listing candidate.', pitch:['jpyr'], isNew:false},
    {name:'Bitkey', url:'https://bitkey.world/', cat:'ウォレット', catEn:'Wallet', desc:'Block Inc.製セルフカストディBitcoinウォレット（アプリ・ハードウェア・リカバリー）', descEn:'Self-custody Bitcoin wallet by Block Inc. App, hardware, and recovery.', pitch:['izakaya'], isNew:false},
    {name:'Blockstream', url:'https://blockstream.com/', cat:'インフラ', catEn:'Infrastructure', desc:'Bitcoinおよびブロックチェーン技術のグローバルリーダー。Adam Back CEO。', descEn:'Global leader in Bitcoin and blockchain technology. Adam Back, CEO.', pitch:['net'], isNew:false},
    {name:'BlockBytes Capital', url:'https://blockbytescapital.io', cat:'資産運用', catEn:'Asset Management', desc:'デジタル資産専門の資産管理会社、規律あるBitcoin長期投資戦略。STOトークン候補。', descEn:'Digital asset-focused asset management firm. Disciplined long-term Bitcoin investment strategy. STO token candidate.', pitch:['sto'], isNew:false},
    {name:'Cake Wallet', url:'https://cakewallet.com', cat:'ウォレット', catEn:'Wallet', desc:'使いやすさ重視の暗号資産ウォレット。IZAKAYA連携候補。', descEn:'User-friendly crypto wallet. IZAKAYA integration candidate.', pitch:['izakaya'], isNew:false},
    {name:'Casa', url:'https://casa.io', cat:'セキュリティ', catEn:'Security', desc:'Bitcoinのセルフカストディセキュリティ企業、マルチシグウォレット', descEn:'Bitcoin self-custody security company. Multisig wallet.', pitch:['izakaya'], isNew:false},
    {name:'Cash App', url:'https://cash.app/bitcoin', cat:'フィンテック', catEn:'Fintech', desc:'低コストでBitcoinの購入・利用・獲得ができるアプリ。Block傘下。JPYR統合候補。', descEn:'App to buy, use, and earn Bitcoin at low cost. Under Block. JPYR integration candidate.', pitch:['jpyr'], isNew:false},
    {name:'CitizenX', url:'http://citizenx.com', cat:'市民権・投資移民', catEn:'Citizenship/Investment Migration', desc:'世界初の市民権マーケット、Bitcoin対応国へのパスポート取得支援', descEn:'World\'s first citizenship marketplace. Passport acquisition for Bitcoin-friendly countries.', pitch:['net'], isNew:false},
    {name:'Deloitte', url:'https://www.deloitte.com', cat:'コンサルティング', catEn:'Consulting', desc:'10年超のデジタル資産・ブロックチェーン実績を持つグローバルコンサルファーム。STO規制対応コンサルとして関係構築価値あり。', descEn:'Global consulting firm with 10+ years of digital asset and blockchain experience. Valuable as STO regulatory consulting partner.', pitch:['sto'], isNew:false},
    {name:'Digital Ascension Group', url:'https://www.digitalfamilyoffice.io/', cat:'ウェルスマネジメント', catEn:'Wealth Management', desc:'🆕 ダラス拠点、暗号資産専門のマルチファミリーオフィス。STOトークンの富裕層投資家候補。', descEn:'Dallas-based crypto-focused multi-family office. STO token high-net-worth investor candidate.', pitch:['sto'], isNew:true},
    {name:'Ellipal', url:'https://www.ellipal.com/', cat:'ウォレット', catEn:'Wallet', desc:'Forbes推奨のエアギャップ型ハードウェアウォレット。IZAKAYA連携候補。', descEn:'Forbes-recommended air-gapped hardware wallet. IZAKAYA integration candidate.', pitch:['izakaya'], isNew:false},
    {name:'Exodus', url:'https://www.exodus.com', cat:'ウォレット', catEn:'Wallet', desc:'マルチアセットウォレット。JP Richardson CEOはスピーカー。JPYR上場・IZAKAYA連携の最優先候補。', descEn:'Multi-asset wallet. JP Richardson CEO is a speaker. Top priority for JPYR listing and IZAKAYA integration.', pitch:['jpyr','izakaya'], isNew:false},
    {name:'Fold', url:'https://foldapp.com', cat:'フィンテック', catEn:'Fintech', desc:'Bitcoin金融サービスプラットフォーム、デビットカード・ギフトカードでBitcoin獲得。JPYR統合候補。', descEn:'Bitcoin financial services platform. Earn Bitcoin with debit and gift cards. JPYR integration candidate.', pitch:['jpyr'], isNew:false},
    {name:'Fortitude Mining', url:'https://fortitudemining.com/', cat:'マイニング', catEn:'Mining', desc:'DCGネットワーク傘下の機関投資家グレードBitcoinマイニング企業', descEn:'Institutional-grade Bitcoin mining company under DCG network.', pitch:['net'], isNew:false},
    {name:'Foundation', url:'https://foundation.xyz', cat:'ウォレット', catEn:'Wallet', desc:'米国製オープンソースBitcoinウォレット「Passport Prime」。IZAKAYA連携候補。', descEn:'US-made open-source Bitcoin wallet "Passport Prime". IZAKAYA integration candidate.', pitch:['izakaya'], isNew:false},
    {name:'FV Bank', url:'http://www.fvbank.us/', cat:'銀行', catEn:'Banking', desc:'プエルトリコ規制のデジタルバンク、デジタル資産カストディ統合。JPYR銀行パートナー候補。', descEn:'Puerto Rico-regulated digital bank with digital asset custody integration. JPYR banking partner candidate.', pitch:['jpyr'], isNew:false},
    {name:'Geneva International', url:'https://geneva-ppli.com/', cat:'保険・金融', catEn:'Insurance/Finance', desc:'プライベートプレースメント生命保険(PPLI)の専門家集団。富裕層向けSTOトークン構造で連携可能。', descEn:'Private Placement Life Insurance (PPLI) specialists. Potential collaboration for HNW-targeted STO token structure.', pitch:['sto'], isNew:false},
    {name:'Giga Energy', url:'https://gigaenergy.com', cat:'エネルギー・インフラ', catEn:'Energy/Infrastructure', desc:'AI・データセンター向け電力・冷却インフラ、1.8GW超の電力インフラ納入実績', descEn:'Power and cooling infrastructure for AI and data centers. 1.8GW+ power infrastructure delivered.', pitch:['net'], isNew:false},
    {name:'GOAT Network', url:'https://www.goat.network/', cat:'ブロックチェーン', catEn:'Blockchain', desc:'Bitcoin Native ZKロールアップ、持続可能なBTC利回り。IZAKAYAウォレット統合候補。', descEn:'Bitcoin-native ZK rollup with sustainable BTC yield. IZAKAYA wallet integration candidate.', pitch:['izakaya'], isNew:false},
    {name:'HIVE Digital Technologies', url:'https://hivedigitaltechnologies.com', cat:'データセンター', catEn:'Data Center', desc:'カナダ・スウェーデン・パラグアイで再生可能エネルギー活用のTier1/3データセンター運営', descEn:'Operates Tier 1/3 data centers using renewable energy in Canada, Sweden, and Paraguay.', pitch:['net'], isNew:false},
    {name:'Inpay', url:'https://www.inpay.com', cat:'決済', catEn:'Payments', desc:'デンマーク金融庁規制、200カ国以上へのリアルタイム決済インフラ。JPYR決済パートナー候補。', descEn:'Danish FSA-regulated real-time payment infrastructure for 200+ countries. JPYR payment partner candidate.', pitch:['jpyr'], isNew:false},
    {name:'KPMG', url:'https://home.kpmg', cat:'会計・コンサルティング', catEn:'Accounting/Consulting', desc:'グローバル大手会計事務所、デジタル資産部門。STO監査・コンプライアンスパートナー候補。', descEn:'Global Big Four accounting firm with digital asset division. STO audit and compliance partner candidate.', pitch:['sto'], isNew:false},
    {name:'Syz Capital', url:'https://syz.com', cat:'資産運用', catEn:'Asset Management', desc:'スイスの資産運用会社。欧州機関投資家へのSTOトークン紹介窓口として有望。', descEn:'Swiss asset management firm. Promising gateway to European institutional investors for STO token.', pitch:['sto'], isNew:true},
    {name:'VanEck', url:'https://www.vaneck.com', cat:'資産運用', catEn:'Asset Management', desc:'大手資産運用会社、Bitcoin ETF。運用資産800億ドル超。STOトークンの機関投資家パートナー候補。', descEn:'Major asset manager with Bitcoin ETF. $80B+ AUM. STO token institutional partner candidate.', pitch:['sto'], isNew:true},
  ]
};

const speakerTwitter = {
  'Michael Saylor':'saylor',
  'Jack Mallers':'jackmallers',
  'David Marcus':'davidmarcus',
  'Dave Ripley':'daveripley',
  'Alex Leishman':'alex_leishman',
  'JP Richardson':'jprichardson',
  'Arthur Hayes':'CryptoHayes',
  'Jeff Booth':'JeffBooth',
  'Simon Gerovich':'gerovich',
  'Alexander Blume':'TwoPrimeHQ',
  'Phong Le':'phong_le',
  'Derar Islim':'DerarIslim',
  'Adam Reeds':'ledn_io',
  'Frank Holmes':'USFundsinvestor',
  'Caitlin Long':'CaitlinLong_',
  'Brent Johnson':'SantiagoAuFund',
  'Alex Thorn':'intangiblecoins',
  'Faryar Shirzad':'FaryarShirzad',
  'Miles Suter':'milessuter',
  'Marty Bent':'MartyBent',
  'Matt Odell':'ODELL',
  'Fred Thiel':'FrederickThiel',
  'David Bailey':'bquittem',
  'Paul Atkins':'SECGov',
  'Mike Selig':'CFTC',
  'Cynthia Lummis':'CynthiaMLummis',
  'Patrick Witt':'PatrickWitt',
  'Eric Trump':'EricTrump',
  'Adam Back':'adam3us',
  'Natalie Brunell':'natbrunell',
  'Peter McCormack':'PeterMcCormack',
  'Aaron Arnold':'AltcoinDailyio',
  'Paul Grewal':'paulgrewal',
  'Alex Gladstein':'gladstein',
  'Curtis Yarvin':'curtis_yarvin',
  'Danielle DiMartino Booth':'DiMartinoBooth',
  'Aaron van Wirdum':'AaronvanW',
  'Kenny Florian':'KennyFlorian',
  'Aaron Ginn':'aginnt',
  'Alex Pruden':'p11qtm',
  'Matt Schultz':'mattcshultz',
  'Irene Gao':'BITMAINtech',
  'Paolo Ardoino':'paaborner',
  'Tim Draper':'TimDraper',
  'Amy Oldenburg':'amyoldenburg',
  'Tarek Mansour':'tarekmansour',
  'Bernie Moreno':'berniemoreno',
  'Amanda Fabiano':'AmandaFabiano',
  'Anaise Kanimba':'AnaiseFaith',
  'Andrew Begin':'andrewbegin',
  'Alexandre Laizet':'AlexandreLaizet',
};

const speakerWebsite = {
  'Jack Mallers':'https://strike.me',
  'David Marcus':'https://www.lightspark.com',
  'Dave Ripley':'https://www.kraken.com',
  'Alex Leishman':'https://river.com',
  'JP Richardson':'https://www.exodus.com',
  'Mike Belshe':'https://www.bitgo.com',
  'Arthur Hayes':'https://maelstrom.fund',
  'Jeff Booth':'https://egodeathcapital.com',
  'Simon Gerovich':'https://metaplanet.jp',
  'Alexander Blume':'https://twoprime.io',
  'Michael Saylor':'https://www.strategy.com',
  'Phong Le':'https://www.strategy.com',
  'Derar Islim':'https://www.antalpha.com',
  'Adam Reeds':'https://ledn.io',
  'Frank Holmes':'https://www.usfunds.com',
  'Caitlin Long':'https://custodiabank.com',
  'Brent Johnson':'https://www.santiagocapital.com',
  'Charles Edwards':'https://capriole.io',
  'Alex Thorn':'https://www.galaxy.com',
  'Faryar Shirzad':'https://www.coinbase.com',
  'Miles Suter':'https://block.xyz',
  'Marty Bent':'https://tftc.io',
  'Matt Odell':'https://ten31.vc',
  'Fred Thiel':'https://www.mara.com',
  'Matt Schultz':'https://www.cleanspark.com',
  'David Bailey':'https://nakamoto.com',
  'Irene Gao':'https://www.bitmain.com',
  'Paul Atkins':'https://www.sec.gov',
  'Cynthia Lummis':'https://www.lummis.senate.gov',
  'Patrick Witt':'https://www.whitehouse.gov',
  'Eric Trump':'https://americanbitcoin.com',
  'Adam Back':'https://blockstream.com',
  'Natalie Brunell':'https://coinStories.com',
  'Peter McCormack':'https://www.whatbitcoindid.com',
  'Aaron Arnold':'https://www.altcoindaily.co',
  'Paul Grewal':'https://www.coinbase.com',
  'Alex Gladstein':'https://hrf.org',
  'Alex von Frankenberg':'https://hightech-gruenderfonds.de',
  'Alex Pruden':'https://www.projecteleven.com',
  'Roberto Rios':'https://limaresearch.co',
  'Aaron Daniel':'https://resolvr.io',
  'Aaron Ginn':'https://hydrahost.com',
  'Aaron van Wirdum':'https://bitcoinmagazine.com',
  'Alessandro Cecere':'https://eldorado.io',
  'Alex Lewin':'https://www.fedi.xyz',
  'Jörg Guido Hülsmann':'https://mises.org',
  'Kenny Florian':'https://www.kennyflorian.com',
  'Paolo Ardoino':'https://tether.to',
  'Tim Draper':'https://www.draper.vc',
  'Amy Oldenburg':'https://www.morganstanley.com',
  'Tarek Mansour':'https://kalshi.com',
  'Bernie Moreno':'https://www.moreno.senate.gov',
  'Amanda Fabiano':'https://nakamoto.com',
  'Anaise Kanimba':'https://africabitcoininstitute.org',
  'Andrew Begin':'https://galoy.io',
  'Alexandre Laizet':'https://capitalb.com',
};

const sponsorTwitter = {
  'Antalpha':'Antalpha_',
  'Bitmain':'BITMAINtech',
  'Block':'blocks',
  'CleanSpark':'CleanSparkInc',
  'Frax':'fraxfinance',
  'Gemini':'Gemini',
  'MARA':'MARAHoldings',
  'Metaplanet':'Metaplanet_JP',
  'Nakamoto':'nakamoto',
  'Robinhood':'RobinhoodApp',
  'American Bitcoin':'AmericanBitcoin',
  'BitGo':'BitGo',
  'Cake Wallet':'cakewallet',
  'Crypto.com':'cryptocom',
  'Human Rights Foundation':'HRF',
  'Kraken Institutional':'krakenfx',
  'Riot Platforms':'RiotPlatforms',
  'SALT Lending':'SaltLending',
  'Two Prime':'TwoPrimeHQ',
  'Unchained':'unchained',
  'Bitdeer':'BitdeerOfficial',
  'Blockware Solutions':'blockwaremining',
  'Calamos':'Calamos',
  'eToro':'eToro',
  'Layer Two Labs':'LayerTwoLabs',
  'Ledn':'ledn_io',
  'VanEck':'vaneck_us',
  'Polymarket':'Polymarket',
  'Stand With Crypto':'StandWithCrypto',
  'Syz Capital':'SyzGroup',
  'Travala':'travalacom',
  'a16z crypto':'a16zcrypto',
  'Amplify ETFs':'amplifyetfs',
  'Arch Lending':'ArchLending',
  'Avalon Labs':'avalonfinance_',
  'Aven':'Aven_com',
  'BinanceUS':'BinanceUS',
  'Bitkey':'bitkeyworld',
  'Blockstream':'Blockstream',
  'Casa':'CasaHODL',
  'Cash App':'CashApp',
  'Deloitte':'Deloitte',
  'Ellipal':'ellipalwallet',
  'EMCD':'emcdpool',
  'Exodus':'exodus_io',
  'Fold':'FoldApp',
  'Foundation':'foundationdevices',
  'FV Bank':'FVBank',
  'Giga Energy':'gigaenergy',
  'GOAT Network':'GOATRollup',
  'GOWD':'GOWDapp',
  'Hashera':'hashera_io',
  'HIVE Digital Technologies':'HIVEDigitalTech',
  'Hydra Host':'hydrahost',
  'Inpay':'InpayX',
  'Katten':'KattenLaw',
  'KPMG':'KPMG',
  'BlockBytes Capital':'BlockBytesHQ',
};

const sponsorLogos = {
  'a16z crypto':'69a6f9c8a9d20e9248bb44f2_a16z-logo.webp',
  'American Bitcoin':'68fa8d7682f2d95c602f898c_680f8e2649639ce17c3a8d66_abtc-20-20logo-20primary-20-20navy-20-20ryan-20k.webp',
  'Amplify ETFs':'68fa8de56ed8c4845793f99b_680a55cf8321d124f800acf6_amp002-tm-logo-rgb-2c-jennifer-hasbrouck.webp',
  'Antalpha':'691dde5439c05527faa4dc9d_logo_v_color-3x.webp',
  'Apex Capital Partners':'68fa8cfa6ed8c484579399d3_65aabba9441c60554e3e20ec_apex-20capital-20black-20-26-20gold-20-20corinne-20frankel.webp',
  'Arch Lending':'68fa8d836ed8c4845793cc8e_667470dfcaaa33688508acdb_logo-20-20original.webp',
  'AsicXchange':'68fa8e1e83c2d0b1f92b7b5c_6633f91295a44e1e39527d46_axc-logo_light_svg_3.webp',
  'Avalon Labs':'68fa8de46ed8c4845793f975_68104b1a57189cadbb8975d3_screenshot-202025-04-28-20at-2010-43-55-e2-80-afpm.webp',
  'Aven':'69a706aa60a473d78ef01260_aven.webp',
  'BinanceUS':'69ab56f09e38cf28c033d934_500c0330-bc52-4279-8ab9-4706118f3880-ticket-hs_file_upload-b-us_logo-long_yellow-34fa5f.webp',
  'Bitdeer':'68fa8d836ed8c4845793cc78_bitdeer-recOJrbddB6v4c5RO.webp',
  'BitGo':'691de14339c05527faa6bb20_67b3651867f4051b6fcae38f_full-20logo_light-20-20carolyn-20pham.webp',
  'Bitkey':'68fa8e0b5c81b5b04f39e74b_6813cf8ce68bd25229bae58d_bitkey-20logo-20black-20-1-20-20william-20samme.webp',
  'BITMAIN':'691dde463b3ce620c7eb7030_bitmain-reclQwVoqWj89ELLw.webp',
  'Block':'69a9c4bafa91632f9706f80e_blocklogo.webp',
  'BlockBytes Capital':'698a2b555132d5d4d066789e_screenshot-2026-02-09-at-12-44-45-pm.webp',
  'Blockstream':'68fa8da06ed8c4845793db2b_blockstream-recRrCXXVlBTsaTQo.webp',
  'Blockware Solutions':'68fa7b23bc24f0bbb02beb5e_blockware-solutions-recAJByNYjMYCtprO.webp',
  'BrainSprout Studios':'6980c07e75193b418536fd19_604fe198-62a1-4e1c-8f03-4dcc8f65f9b4-ticket-hs_file_upload-logo-4-3f4a10.webp',
  'Cake Wallet':'691de10639c05527faa688b9_cake-wallet-recg4Wc3mTQCC5RJJ.webp',
  'Calamos':'68fa8cfa6ed8c484579399df_682b443047b9999cb156ce69_image001-20-1.webp',
  'Canaan':'69bd7284f3577882abe1513b_canaan-new.webp',
  'Casa':'68fa8cfa6ed8c484579399e8_66872f99ea3e3a0992e79a82_22-casa-logo-20-1.webp',
  'Cash App':'69a9c6b864dd03d5e34173f5_cashapplogo.webp',
  'CitizenX':'68fa8e2bc88b45e653fcae96_e811a651-3867-44f4-bbd5-f9374121e698-ticket-hs_file_upload-logotype-standard-black.webp',
  'CleanSpark':'698cd20696e44777bb945338_clsk_vertical_color.webp',
  'Cohen & Company':'68fa8e0b5c81b5b04f39e75a_67f85690e1fc8158b211ba51_logo_ccm_blue.webp',
  'Crypto.com':'691de0fc786e06b8672e5128_crypto-com-reciAqxgD89YeZOvP.png',
  'Data Airflow':'68fa8dc4bac053e9fd21dffd_6718660214a411925de2fd3d_data-airflow.webp',
  'Deloitte':'68fa7b1ae168dfdc6afc92a2_6824b1ef054d88625e907363_deloittelogo_blacktex_greendot_transparentbkgd.webp',
  'Digital Ascension Group':'69851feae7092135421414de_69bc61d3-7ccb-4659-a431-7d55f991e0f0-ticket-hs_file_upload-dag-white-bg-2-31124e.webp',
  'Ellipal':'69401bfaf1ab383f85e1d42c_ellipal-logo-png.webp',
  'EMCD':'68fa8da06ed8c4845793db0c_emcd-top-10-mining-pool-coinhold-p2p-recJGgix6vvlpKp5o.webp',
  'eToro':'6993b86e1ea20e1d45e3bc67_etoro-logo.webp',
  'Evertas':'68fa8cd764aa595af3d3c824_66798b1f0dd5ef4ba918a942_evertas-logo-rgb-20-20antonio-20flores.webp',
  'ExxonMobil':'68fa8d5e83c2d0b1f92b054e_6668b6d171ee214786a91eee_brand-2bcenter-2b-2blogo-2b-2bexxonmobil-2blogo-2b-2bred-2brgb.webp',
  'FARMGOD & ASIC Plug':'693839c8802c7cdfdd096850_asicplug-x-farmgod-logo_transparent.webp',
  'FBOX':'691b7311f02f51c9285eea7b_fbox-logo-reformed-rgb.webp',
  'FinTax':'68fa8cf078450df8b4195dcd_67d23b1ca27d6dbe97d48e1b_fintax-pdf-xingjiang-qin.webp',
  'Fold':'68fa8d0343dfc1d5133f11de_rFOz5eQwRCab_mqkIg7Ubntjvoyikmf9f-Zi9cYlEbk.webp',
  'Fooksum':'6983858eda19ed2fa007e8ea_fooksum.webp',
  'Fortitude Mining':'68fa8e37c4d53930549dca36_67cb445fc36f16efe8e25d7d_fortitude-white-background-lindsay-ciccoricco.webp',
  'Foundation':'68fa8cfa6ed8c484579399fc_6488b0b0fcd2d95f6b83e062_foundation-20logo-20-1.webp',
  'Frax':'6995e05031f221e543ae7256_frax-com-logo-black-cb6941.webp',
  'FV Bank':'68fa8d0343dfc1d5133f11b2_6488b0b0fcd2d95f6b83e059_fv-20bank-20logo-20-1.webp',
  'Gemini':'69b9b321d55e518e499b2da4_gemini-fulllogo-rgb-flare.webp',
  'Geneva International':'68fa8d7682f2d95c602f8999_680a59bd0ce90cc99b6291f4_geneva-international-vertical-transparentbg.webp',
  'Giga Energy':'68fa8cd764aa595af3d3c82a_67f68caec735287dbece18dc_new-20giga-20logo-20blue.webp',
  'GOAT Network':'68fa8e0b5c81b5b04f39e745_goat-network-recxUwTgTF4apNFYF.webp',
  'GOWD':'68fa8d7682f2d95c602f89a5_67acc8a50da414e9127f3929_logo-20final-20gowd-20crypto-20friendly.webp',
  'Hangzhou CADRO Computing':'69746d2f4d35d034a39155d1_ezgif-569afcce9931ddaa-1.webp',
  'Hashera':'691dce2a708d60076460a53d_hashera.webp',
  'HashHouse':'69bad22c057caa2bcaf603b8_hash-house.webp',
  'Heritage Auctions':'68fa8d2564aa595af3d3ec52_65d8cde11ce006b2c3ea74b1_ha-logo.webp',
  'HIVE Digital Technologies':'697a94c7f8e25b7344c944a0_hive_digital_technologies_bee_vertical_black.webp',
  'Human Rights Foundation':'68fa8dd0c4d53930549d982f_6620350e615921022264c26d_untitled-20design-20-1-20-1.webp',
  'Hydra Host':'698f62656dd12a42e4b16803_hydra-host-logo.webp',
  'Inpay':'6980be45d575c7959a2a85ed_inpay_logo_green_rgb-gina-bukovecz.webp',
  'Intelliflex':'68fa8da978450df8b41989ff_6488b0b0fcd2d95f6b83e3be_intelliflex.webp',
  'JH Marlin Law':'69b0553daf0f2a1b09102ac9_jhmglobal_logo_vertical_vf.webp',
  'Katten':'68fa8cf078450df8b4195dc4_6808170b85c29377665df090_katten_logo_blue_cmyk_100-75-2-18-20-20kristen-20machat.webp',
  'KPMG':'69a861d34d797389db551975_6488b0b0fcd2d95f6b83e26f_629f8b813dd89dbfc8168d26_kpmg_nocp_rgb.webp',
  'Kraken Institutional':'69b05834082c9774307dc59a_kraken-institutional-stacked.webp',
};
